#!/usr/bin/env python3

import sys, argparse, os, re
from argparse import Namespace
from bs4 import BeautifulSoup
import util
from util import warn, die, getPage, debug
import time

def quest(args: Namespace, contestName: str) -> dict[str, str]:
    qlist = 'qlist.html'
    if args.contest or not os.path.exists(qlist):
        url = f'https://atcoder.jp/contests/{contestName}/tasks'
        time.sleep(0.2)
        page = getPage(url)
        with open(qlist, 'w', encoding='UTF-8') as wfp:
            print(page, file=wfp, end='')
    with open(qlist, 'r', encoding='UTF-8') as fp:
        soup = BeautifulSoup(fp, 'lxml')
    qdict = {}
    for row in soup.table.find_all('tr')[1:]:    # type: ignore
        qdict[row.a.string.lower()] = 'https://atcoder.jp' + row.a.attrs['href']    # type: ignore
    if args.all_questions:
        return qdict
    retv = {}
    for x in args.quest:
        xx = x.lower()
        if xx not in qdict: die(f'Unknown question {x}')
        retv[xx] = qdict[xx]
    # debug("retv", retv)
    return retv

# We assume that samples are in <h3> tags....
def extractEg(qid: str, page: str) -> None:
    def sub(tag, exp: str, dic: dict[str, str]) -> None:
        if not tag.string: return
        mo = re.search(exp, tag.string)
        if not mo: return
        while tag:
            tag = tag.next_sibling
            if tag.name == 'pre': break
            if 'find_all' in dir(tag) and tag.find_all('pre'):
                tag = tag.pre
                break
        if not tag:
            print("Warning: Failed to find pre tag.", file=sys.stderr)
            return
        dic[mo[1]] = tag.string.strip() if tag.string else ''

    soup = BeautifulSoup(page, 'lxml')
    ins: dict[str, str] = {}
    outs: dict[str, str] = {}
    for tag in soup.find_all('h3'):
        sub(tag, r'(?:Sample\s*Input|入力例)\s*(\d+)', ins)
        sub(tag, r'(?:Sample\s*Output|出力例)\s*(\d+)', outs)
    for i in ins:
        if i not in outs: continue
        infile  = f'{qid}/{util.in_file(i)}'
        outfile = f'{qid}/{util.exp_file(i)}'
        # if fKeep and (os.path.exists(infile) or os.path.exists(outfile)):
        #     continue
        with open(infile, 'w') as wfp:
            if ins[i]:
                print(ins[i], file=wfp)
        with open(outfile, 'w') as wfp:
            if outs[i]:
                print(outs[i], file=wfp)

def makeMakefile(path: str) -> None:
    with open(path, 'w', encoding='UTF-8') as wfp:
        print('''
CXX := g++

ifeq ($(DEBUG),)
  DEBUGFLAGS := -O2
else
  DEBUGFLAGS := -g -O0 -D_GLIBCXX_DEBUG -DDEBUG=1 -fsanitize=address,undefined -fno-sanitize-recover -fno-omit-frame-pointer
  ifneq ($(DEBUG_LIB),)
    DEBUGFLAGS := $(DEBUGFLAGS) -DDEBUG_LIB=1
  endif
endif

WARNINGS := -Wall -Wno-format-security -Wshadow -fconcepts

CXXFLAGS := -std=gnu++23 $(DEBUGFLAGS) $(WARNINGS)

CXXFLAGS := $(CXXFLAGS) -I/home/y-tanabe/lib/boost_1_73_0
CXXFLAGS := $(CXXFLAGS) -I/home/y-tanabe/proj/compprog/clib/ac-library
CXXFLAGS := $(CXXFLAGS) $(if $(CMPNAIVE),-DCMPNAIVE=1)
CXXFLAGS := $(CXXFLAGS)

all: cans

clean:
	$(RM) cans.o cans cans.exe *~ *.stackdump core
''', file=wfp)

def makeSource(path: str) -> None:
    with open(path, 'w', encoding='UTF-8') as wfp:
        print('''#include <bits/stdc++.h>
#include <cassert>
using namespace std;
using ll = long long int;
using u64 = unsigned long long;
using pll = pair<ll, ll>;
// #include <atcoder/all>
// using namespace atcoder;
#define REP(i, a, b) for (ll i = (a); i < (b); i++)
#define REPrev(i, a, b) for (ll i = (a); i >= (b); i--)
#define ALL(coll) (coll).begin(), (coll).end()
#define SIZE(v) ((ll)((v).size()))
#define REPOUT(i, a, b, exp, sep) REP(i, (a), (b)) cout << (exp) << (i + 1 == (b) ? "" : (sep)); cout << "\\n"

// @@ !! LIM()

int main(/* int argc, char *argv[] */) {
  ios_base::sync_with_stdio(false);
  cin.tie(nullptr);
  cout << setprecision(20);

  return 0;
}
''', file=wfp)

def doQuest(qid: str, url: str) -> None:
    # debug('doQuest ', qid, url)
    if not os.path.exists(qid):
        os.mkdir(qid)
    p = f'{qid}/q.html'
    time.sleep(0.2)
    page = getPage(url)
    with open(p, 'w', encoding='UTF-8') as wfp:
        print(page, end='', file=wfp)
    with open(p, 'r', encoding='UTF-8') as fp:
        page = fp.read()
        # It may seem that in the case of
        # "not (fKeep and os.apth.exists(p)" you do not need to read again,
        # but this code forces translation from \r\n to \n.
    extractEg(qid, page)

    makeMakefile(f'{qid}/Makefile')
    makeSource(f'{qid}/cans.cc')

def getContestName(name: str) -> str:
    cnFile = ".contestName"
    if name:
        with open(cnFile, 'w') as wfp:
            print(name, file=wfp)
        return name
    if os.path.exists(cnFile):
        with open(cnFile, 'r') as fp:
            return fp.readline().strip()
    return os.path.basename(os.getcwd())

def main() -> None:
    args = parseArgs()

    if args.url:
        qdict = {args.url[-1]: args.url}
    elif args.quest or args.all_questions:
        qdict = quest(args, getContestName(args.contest))
    else:
        die('No question is specified.')

    for q in qdict:
        if os.path.exists(q):
            die(f'File or directory {q} exists.')

    warn('Processing ', end='')
    for q in qdict:
        warn(q, end='... ')
        doQuest(q, qdict[q])
    warn('Done.')

def parseArgs() -> Namespace:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description='''
Reads AtCoder questions, extracts input/output examples, makes a makefile 
and cans.cc.  

Examples:
  * qread --url=https://atcoder.jp/contests/abc398/tasks/abc398_a
      Read a single question.
  * qread --contest abc398 a b c
      Read questions a, b and c of Contest abc398.
  * qread d e
      Read questions d and e.  If qread has been executed in this directory,
      the same contest is used.  Otherwise, the name of the current directory
      is assumed as the contest name.
  * qread --all_questions
      Read all questions of the contest.
'''
    )
    parser.add_argument(
        '--url', type=str,
        help='''Problem URL.  If specified, --all_questions, --contest 
        and quest are ignored.
        The question identifier is taken from the last letter of the URL.
        ''')
    parser.add_argument(
        '--contest', type=str,
        help='''Contest identifier, such as abc147 or tdpc.
        If not specified, it is taken from the most recently specified name,
        which has been saved into ./.contestName, or the directory name.
        ''')
    # It is dangerous to define one character '-c' option, because when
    # the user mistakingly typed `-contest abc`, it is interpreted as
    # `-c ontest abc`.
    parser.add_argument(
        '-a', '--all_questions', action='store_true',
        help='All questions will be retrieved.')
    parser.add_argument(
        'quest', type=str, nargs='*',
        help='question identifier such as a or f')
    return parser.parse_args()

main()
